### ISSUE TITLE
New cubes do not work with Julia API

### ISSUE THREAD

**Issue by meggart** [esa-esdl/esdl-core#74]
Currently the new generated data cubes can not be used from the Julia API because for new variables there is a mismatch between the folder name and the NetCDF variable name. For example in the folder file `esdc-8d-0.25deg-1x720x1440-1.0.2_2/data/cloud_cee/2001_cee.nc` the variable is named `cee` where our convention would expect the variable `cloud_cee` to match the folder name. Is it possible to either rename the variables or the folders and file names? @dzelge

**Comment by dzelge** [comment]
Ich habe die Verzeichnisse umbenannt. Wen ich ein bisshcne Zeit habe, werde ich die prefixe wieder einfuehren. Das kostet aber Zeit.HFabian Gans <notifications@github.com> hat am 12. November 2018 um 08:23 geschrieben:  Currently the new generated data cubes can not be used from the Julia API because for new variables there is a mismatch between the folder name and the NetCDF variable name. For example in the folder file esdc-8d-0.25deg-1x720x1440-1.0.2_2/data/cloud_cee/2001_cee.nc the variable is named cee where our convention would expect the variable cloud_cee to match the folder name. Is it possible to either rename the variables or the folders and file names? @dzelge—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by forman** [comment]
@dzelge For what reason have you changed them?

**Comment by meggart** [comment]
I think this is resolved...
